registry:
  type: harbor
  url: harbor.demotechhub.xyz
  namespace: ft-backend

deployment:
  type: docker-compose

target:
  type: server
  host: app-host-01
  port: 22

application:
  path: /data/apps/test/dev
  compose_file: compose.yml
  deploy_script: deploy/deploy.sh
  rollback_script: deploy/rollback.sh


health_check:
  enabled: false
  target: compose
  timeout: 180
