registry:
  type: harbor
  url: harbor.demotechhub.xyz
  namespace: jenkins-pipeline-poc-github-app

deployment:
  type: docker-compose

target:
  type: server
  host: app-host-01
  port: 22

application:
  path: /data/apps/jenkins-pipeline-poc-github-app
  compose_file: compose.yml
  deploy_script: deploy/deploy.sh
  rollback_script: deploy/rollback.sh
  health_check_script: deploy/health-check.sh


health_check:
  enabled: true
  target: compose
  timeout: 180