registry:
  type: ecr
  url: 123456789012.dkr.ecr.ap-south-1.amazonaws.com
  namespace: ft-backend
  aws_region: ap-south-1

deployment:
  type: ecs

target:
  type: ecs
  cluster: ft-backend-prod
  service: backend

health_check:
  enabled: true
  target: ecs
  timeout: 120